In [1]:
import numpy as np
import pandas as pd


In [7]:
# import the dataset into the dataframe

df=pd.read_csv("C:/Users/Brown/Documents/GitHubRepo/Machine_Learning/Social_Network_Ads.csv")
df.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [4]:
# feature/independent/predictor


# response/target/dependent/label

In [8]:
# scipy/sklearn machine learning project library for manipulations

In [9]:
df.Purchased.value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [10]:
df.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [15]:
# split the data into feature and target set
x = df[["Gender", "Age", "EstimatedSalary"]] # features

y =df["Purchased"] #Label


# when there is ranking = Ordinal

# no ranking = Norminal

In [16]:
x.head(11)

Gender  Age  EstimatedSalary
0     Male   19            19000
1     Male   35            20000
2   Female   26            43000
3   Female   27            57000
4     Male   19            76000
5     Male   27            58000
6   Female   27            84000
7   Female   32           150000
8     Male   25            33000
9   Female   35            65000
10  Female   26            80000

In [17]:
x1=pd.get_dummies(x, columns=["Gender"])
x1.head(11)

Age  EstimatedSalary  Gender_Female  Gender_Male
0    19            19000              0            1
1    35            20000              0            1
2    26            43000              1            0
3    27            57000              1            0
4    19            76000              0            1
5    27            58000              0            1
6    27            84000              1            0
7    32           150000              1            0
8    25            33000              0            1
9    35            65000              1            0
10   26            80000              1            0

In [66]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier() # the instance of the class

#fit/train the model
model1= dt.fit(x1,y)

In [67]:
er={
    "Gender":["male","male", "female"],
    "Age":[56,40,41],
    "EstimatedSalary":[2737, 1928, 7744]
}

t=pd.DataFrame(er)
t

Gender  Age  EstimatedSalary
0    male   56             2737
1    male   40             1928
2  female   41             7744

In [68]:
t1=pd.get_dummies(t, columns=["Gender"])
t1

Age  EstimatedSalary  Gender_female  Gender_male
0   56             2737              0            1
1   40             1928              0            1
2   41             7744              1            0

In [69]:
model1.predict(t1)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Gender_female
- Gender_male
Feature names seen at fit time, yet now missing:
- Gender_Female
- Gender_Male

  warnings.warn(message, FutureWarning)


array([1, 0, 0], dtype=int64)

In [70]:
x1

Age  EstimatedSalary  Gender_Female  Gender_Male
0     19            19000              0            1
1     35            20000              0            1
2     26            43000              1            0
3     27            57000              1            0
4     19            76000              0            1
..   ...              ...            ...          ...
395   46            41000              1            0
396   51            23000              0            1
397   50            20000              1            0
398   36            33000              0            1
399   49            36000              1            0

[400 rows x 4 columns]

In [71]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [72]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test,= train_test_split(x1, y, test_size=0.2)

In [73]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
model2 = rf.fit(x_train, y_train)

In [74]:
model2.predict(x_test) #predicted values as output

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [75]:
y_predict= model2.predict(x_test)

In [76]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [77]:
confusion_matrix(y_test, y_predict)

array([[44,  7],
       [ 3, 26]], dtype=int64)

In [78]:
y_test.value_counts()

0    51
1    29
Name: Purchased, dtype: int64

In [79]:
accuracy_score(y_test, y_predict)

0.875

In [86]:
from sklearn.svm import SVC

svc = SVC()

model3 = svc.fit(x_train, y_train)

In [87]:
predict3=model3.predict(x_test)

In [88]:
accuracy_score(y_test, predict3)

0.7875

In [132]:
df=pd.read_csv("C:/Users/user/Desktop/Machine Learning/50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [133]:
# split the data into target and feature
y = df.pop("Profit") # Target
X = df.copy() # feagtures 
x

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [141]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [142]:
# convert the state variable to dummie data

X1 = pd.get_dummies(X, columns=["State"])
X1.head()

R&D Spend  Administration  Marketing Spend  State_California  \
0  165349.20       136897.80        471784.10                 0   
1  162597.70       151377.59        443898.53                 1   
2  153441.51       101145.55        407934.54                 0   
3  144372.41       118671.85        383199.62                 0   
4  142107.34        91391.77        366168.42                 0   

   State_Florida  State_New York  
0              0               1  
1              0               0  
2              1               0  
3              0               1  
4              1               0

In [149]:
# Split the data into train and test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X1, y, test_size =0.1)

In [140]:
# building the regression model
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
model5 = lr.fit(x_train, y_train)

In [144]:
# validate the model

model5.predict(x_test)

array([115362.31471541, 159399.17306463, 102837.04257926, 136644.19478425,
       129161.73776513])

In [145]:
y_test

22    110352.25
7     155752.60
28    103282.38
11    144259.40
18    124266.90
Name: Profit, dtype: float64

In [152]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor()

model7 = dt.fit(x_train, y_train)

In [154]:
model7.predict(x_test)

array([ 35673.41,  77798.83, 166187.94,  42559.73, 129917.04])